package handler_test

import (
	"aletheiaware.com/authgo"
	"aletheiaware.com/authgo/authtest"
	"aletheiaware.com/conveyearthgo"
	"aletheiaware.com/conveyearthgo/conveytest"
	"aletheiaware.com/conveyearthgo/database"
	"aletheiaware.com/conveyearthgo/filesystem"
	"aletheiaware.com/conveyearthgo/handler"
	"fmt"
	"github.com/stretchr/testify/assert"
	"html/template"
	"io"
	"net/http"
	"net/http/httptest"
	"os"
	"testing"
)

func TestDelete(t *testing.T) {
	dir, err := os.MkdirTemp("", "test")
	assert.Nil(t, err)
	fs := filesystem.NewOnDisk(dir)
	defer os.RemoveAll(dir)
	tmpl, err := template.New("delete.go.html").Parse(`{{.Error}}{{with .Account}}{{.Username}}{{end}}{{with .Conversation}}{{.Topic}}{{end}}{{with .Message}}{{.Author.Username}}{{end}}{{with .Gift}}{{.Author.Username}}{{end}}`)
	assert.Nil(t, err)
	t.Run("Returns 200 When Signed In And Message Exists", func(t *testing.T) {
		db := database.NewInMemory()
		ev := authtest.NewEmailVerifier()
		auth := authgo.NewAuthenticator(db, ev)
		acc := authtest.NewTestAccount(t, auth)
		token, _ := authtest.SignIn(t, auth)
		am := conveyearthgo.NewAccountManager(db)
		cm := conveyearthgo.NewContentManager(db, fs)
		c, m, _ := conveytest.NewConversation(t, cm, acc)
		mux := http.NewServeMux()
		handler.AttachDeleteHandler(mux, auth, am, cm, tmpl)
		request := httptest.NewRequest(http.MethodGet, fmt.Sprintf("/delete?conversation=%d&message=%d", c.ID, m.ID), nil)
		request.AddCookie(auth.NewSignInSessionCookie(token))
		response := httptest.NewRecorder()
		mux.ServeHTTP(response, request)
		result := response.Result()
		assert.Equal(t, http.StatusOK, result.StatusCode)
		body, err := io.ReadAll(result.Body)
		assert.Nil(t, err)
		assert.Equal(t, authtest.TEST_USERNAME+conveytest.TEST_TOPIC+authtest.TEST_USERNAME, string(body))
	})
	t.Run("Returns 200 When Signed In And Gift Exists", func(t *testing.T) {
		db := database.NewInMemory()
		ev := authtest.NewEmailVerifier()
		auth := authgo.NewAuthenticator(db, ev)
		acc := authtest.NewTestAccount(t, auth)
		token, _ := authtest.SignIn(t, auth)
		am := conveyearthgo.NewAccountManager(db)
		cm := conveyearthgo.NewContentManager(db, fs)
		c, m, _ := conveytest.NewConversation(t, cm, acc)
		g := conveytest.NewGift(t, cm, acc, c, m)
		mux := http.NewServeMux()
		handler.AttachDeleteHandler(mux, auth, am, cm, tmpl)
		request := httptest.NewRequest(http.MethodGet, fmt.Sprintf("/delete?conversation=%d&gift=%d", c.ID, g.ID), nil)
		request.AddCookie(auth.NewSignInSessionCookie(token))
		response := httptest.NewRecorder()
		mux.ServeHTTP(response, request)
		result := response.Result()
		assert.Equal(t, http.StatusOK, result.StatusCode)
		body, err := io.ReadAll(result.Body)
		assert.Nil(t, err)
		assert.Equal(t, authtest.TEST_USERNAME+conveytest.TEST_TOPIC+authtest.TEST_USERNAME, string(body))
	})
	t.Run("Redirects When Not Signed In", func(t *testing.T) {
		db := database.NewInMemory()
		ev := authtest.NewEmailVerifier()
		auth := authgo.NewAuthenticator(db, ev)
		acc := authtest.NewTestAccount(t, auth)
		am := conveyearthgo.NewAccountManager(db)
		cm := conveyearthgo.NewContentManager(db, fs)
		c, m, _ := conveytest.NewConversation(t, cm, acc)
		mux := http.NewServeMux()
		handler.AttachDeleteHandler(mux, auth, am, cm, tmpl)
		request := httptest.NewRequest(http.MethodGet, fmt.Sprintf("/delete?conversation=%d&message=%d", c.ID, m.ID), nil)
		response := httptest.NewRecorder()
		mux.ServeHTTP(response, request)
		result := response.Result()
		assert.Equal(t, http.StatusFound, result.StatusCode)
		u, err := result.Location()
		assert.Nil(t, err)
		assert.Equal(t, fmt.Sprintf("/sign-in?next=%%2Fdelete%%3Fconversation%%3D%d%%26message%%3D%d", c.ID, m.ID), u.String())
	})
	t.Run("Returns 404 When Conversation Does Not Exist", func(t *testing.T) {
		db := database.NewInMemory()
		ev := authtest.NewEmailVerifier()
		auth := authgo.NewAuthenticator(db, ev)
		authtest.NewTestAccount(t, auth)
		token, _ := authtest.SignIn(t, auth)
		am := conveyearthgo.NewAccountManager(db)
		cm := conveyearthgo.NewContentManager(db, fs)
		mux := http.NewServeMux()
		handler.AttachDeleteHandler(mux, auth, am, cm, tmpl)
		// Get
		request := httptest.NewRequest(http.MethodGet, "/delete?conversation=0&message=0", nil)
		request.AddCookie(auth.NewSignInSessionCookie(token))
		response := httptest.NewRecorder()
		mux.ServeHTTP(response, request)
		result := response.Result()
		assert.Equal(t, http.StatusNotFound, result.StatusCode)
		body, err := io.ReadAll(result.Body)
		assert.Nil(t, err)
		assert.Equal(t, http.StatusText(http.StatusNotFound)+"\n", string(body))
		// Post
		request = httptest.NewRequest(http.MethodPost, "/delete?conversation=0&message=0", nil)
		request.AddCookie(auth.NewSignInSessionCookie(token))
		response = httptest.NewRecorder()
		mux.ServeHTTP(response, request)
		result = response.Result()
		assert.Equal(t, http.StatusNotFound, result.StatusCode)
		body, err = io.ReadAll(result.Body)
		assert.Nil(t, err)
		assert.Equal(t, http.StatusText(http.StatusNotFound)+"\n", string(body))
	})
	t.Run("Returns 404 When Message Does Not Exist", func(t *testing.T) {
		db := database.NewInMemory()
		ev := authtest.NewEmailVerifier()
		auth := authgo.NewAuthenticator(db, ev)
		acc := authtest.NewTestAccount(t, auth)
		token, _ := authtest.SignIn(t, auth)
		am := conveyearthgo.NewAccountManager(db)
		cm := conveyearthgo.NewContentManager(db, fs)
		c, m, _ := conveytest.NewConversation(t, cm, acc)
		mux := http.NewServeMux()
		handler.AttachDeleteHandler(mux, auth, am, cm, tmpl)
		// Get
		request := httptest.NewRequest(http.MethodGet, fmt.Sprintf("/delete?conversation=%d&message=%d", c.ID, m.ID+1), nil)
		request.AddCookie(auth.NewSignInSessionCookie(token))
		response := httptest.NewRecorder()
		mux.ServeHTTP(response, request)
		result := response.Result()
		assert.Equal(t, http.StatusNotFound, result.StatusCode)
		body, err := io.ReadAll(result.Body)
		assert.Nil(t, err)
		assert.Equal(t, http.StatusText(http.StatusNotFound)+"\n", string(body))
		// Post
		request = httptest.NewRequest(http.MethodPost, fmt.Sprintf("/delete?conversation=%d&message=%d", c.ID, m.ID+1), nil)
		request.AddCookie(auth.NewSignInSessionCookie(token))
		response = httptest.NewRecorder()
		mux.ServeHTTP(response, request)
		result = response.Result()
		assert.Equal(t, http.StatusNotFound, result.StatusCode)
		body, err = io.ReadAll(result.Body)
		assert.Nil(t, err)
		assert.Equal(t, http.StatusText(http.StatusNotFound)+"\n", string(body))
	})
	t.Run("Returns 404 When Gift Does Not Exist", func(t *testing.T) {
		db := database.NewInMemory()
		ev := authtest.NewEmailVerifier()
		auth := authgo.NewAuthenticator(db, ev)
		acc := authtest.NewTestAccount(t, auth)
		token, _ := authtest.SignIn(t, auth)
		am := conveyearthgo.NewAccountManager(db)
		cm := conveyearthgo.NewContentManager(db, fs)
		c, m, _ := conveytest.NewConversation(t, cm, acc)
		g := conveytest.NewGift(t, cm, acc, c, m)
		mux := http.NewServeMux()
		handler.AttachDeleteHandler(mux, auth, am, cm, tmpl)
		// Get
		request := httptest.NewRequest(http.MethodGet, fmt.Sprintf("/delete?conversation=%d&gift=%d", c.ID, g.ID+1), nil)
		request.AddCookie(auth.NewSignInSessionCookie(token))
		response := httptest.NewRecorder()
		mux.ServeHTTP(response, request)
		result := response.Result()
		assert.Equal(t, http.StatusNotFound, result.StatusCode)
		body, err := io.ReadAll(result.Body)
		assert.Nil(t, err)
		assert.Equal(t, http.StatusText(http.StatusNotFound)+"\n", string(body))
		// Post
		request = httptest.NewRequest(http.MethodPost, fmt.Sprintf("/delete?conversation=%d&gift=%d", c.ID, g.ID+1), nil)
		request.AddCookie(auth.NewSignInSessionCookie(token))
		response = httptest.NewRecorder()
		mux.ServeHTTP(response, request)
		result = response.Result()
		assert.Equal(t, http.StatusNotFound, result.StatusCode)
		body, err = io.ReadAll(result.Body)
		assert.Nil(t, err)
		assert.Equal(t, http.StatusText(http.StatusNotFound)+"\n", string(body))
	})
	t.Run("Returns 404 When Missing Parameter", func(t *testing.T) {
		db := database.NewInMemory()
		ev := authtest.NewEmailVerifier()
		auth := authgo.NewAuthenticator(db, ev)
		acc := authtest.NewTestAccount(t, auth)
		token, _ := authtest.SignIn(t, auth)
		am := conveyearthgo.NewAccountManager(db)
		cm := conveyearthgo.NewContentManager(db, fs)
		c, _, _ := conveytest.NewConversation(t, cm, acc)
		mux := http.NewServeMux()
		handler.AttachDeleteHandler(mux, auth, am, cm, tmpl)
		request := httptest.NewRequest(http.MethodGet, fmt.Sprintf("/delete?conversation=%d", c.ID), nil)
		request.AddCookie(auth.NewSignInSessionCookie(token))
		response := httptest.NewRecorder()
		mux.ServeHTTP(response, request)
		result := response.Result()
		assert.Equal(t, http.StatusNotFound, result.StatusCode)
		body, err := io.ReadAll(result.Body)
		assert.Nil(t, err)
		assert.Equal(t, http.StatusText(http.StatusNotFound)+"\n", string(body))
	})
	t.Run("Conversation As Author", func(t *testing.T) {
		db := database.NewInMemory()
		ev := authtest.NewEmailVerifier()
		auth := authgo.NewAuthenticator(db, ev)
		acc := authtest.NewTestAccount(t, auth)
		token, _ := authtest.SignIn(t, auth)
		am := conveyearthgo.NewAccountManager(db)
		cm := conveyearthgo.NewContentManager(db, fs)
		c, m, _ := conveytest.NewConversation(t, cm, acc)
		mux := http.NewServeMux()
		handler.AttachDeleteHandler(mux, auth, am, cm, tmpl)
		request := httptest.NewRequest(http.MethodPost, fmt.Sprintf("/delete?conversation=%d&message=%d", c.ID, m.ID), nil)
		request.AddCookie(auth.NewSignInSessionCookie(token))
		response := httptest.NewRecorder()
		mux.ServeHTTP(response, request)
		result := response.Result()
		assert.Equal(t, http.StatusFound, result.StatusCode)
		u, err := result.Location()
		assert.Nil(t, err)
		assert.Equal(t, "/", u.String())
	})
	t.Run("Message As Author", func(t *testing.T) {
		db := database.NewInMemory()
		ev := authtest.NewEmailVerifier()
		auth := authgo.NewAuthenticator(db, ev)
		acc := authtest.NewTestAccount(t, auth)
		token, _ := authtest.SignIn(t, auth)
		am := conveyearthgo.NewAccountManager(db)
		cm := conveyearthgo.NewContentManager(db, fs)
		c, m, _ := conveytest.NewConversation(t, cm, acc)
		r, _ := conveytest.NewReply(t, cm, acc, c, m)
		mux := http.NewServeMux()
		handler.AttachDeleteHandler(mux, auth, am, cm, tmpl)
		request := httptest.NewRequest(http.MethodPost, fmt.Sprintf("/delete?conversation=%d&message=%d", c.ID, r.ID), nil)
		request.AddCookie(auth.NewSignInSessionCookie(token))
		response := httptest.NewRecorder()
		mux.ServeHTTP(response, request)
		result := response.Result()
		assert.Equal(t, http.StatusFound, result.StatusCode)
		u, err := result.Location()
		assert.Nil(t, err)
		assert.Equal(t, fmt.Sprintf("/conversation?id=%d#message%d", c.ID, m.ID), u.String())
	})
	// TODO Message Not Author
	t.Run("Message With Reply", func(t *testing.T) {
		db := database.NewInMemory()
		ev := authtest.NewEmailVerifier()
		auth := authgo.NewAuthenticator(db, ev)
		acc := authtest.NewTestAccount(t, auth)
		token, _ := authtest.SignIn(t, auth)
		am := conveyearthgo.NewAccountManager(db)
		cm := conveyearthgo.NewContentManager(db, fs)
		c, m, _ := conveytest.NewConversation(t, cm, acc)
		conveytest.NewReply(t, cm, acc, c, m)
		mux := http.NewServeMux()
		handler.AttachDeleteHandler(mux, auth, am, cm, tmpl)
		request := httptest.NewRequest(http.MethodPost, fmt.Sprintf("/delete?conversation=%d&message=%d", c.ID, m.ID), nil)
		request.AddCookie(auth.NewSignInSessionCookie(token))
		response := httptest.NewRecorder()
		mux.ServeHTTP(response, request)
		result := response.Result()
		assert.Equal(t, http.StatusOK, result.StatusCode)
		body, err := io.ReadAll(result.Body)
		assert.Nil(t, err)
		assert.Equal(t, conveyearthgo.ErrDeletionNotPermitted.Error()+authtest.TEST_USERNAME+conveytest.TEST_TOPIC+authtest.TEST_USERNAME, string(body))
	})
	t.Run("Message With Gift", func(t *testing.T) {
		db := database.NewInMemory()
		ev := authtest.NewEmailVerifier()
		auth := authgo.NewAuthenticator(db, ev)
		acc := authtest.NewTestAccount(t, auth)
		token, _ := authtest.SignIn(t, auth)
		am := conveyearthgo.NewAccountManager(db)
		cm := conveyearthgo.NewContentManager(db, fs)
		c, m, _ := conveytest.NewConversation(t, cm, acc)
		conveytest.NewGift(t, cm, acc, c, m)
		mux := http.NewServeMux()
		handler.AttachDeleteHandler(mux, auth, am, cm, tmpl)
		request := httptest.NewRequest(http.MethodPost, fmt.Sprintf("/delete?conversation=%d&message=%d", c.ID, m.ID), nil)
		request.AddCookie(auth.NewSignInSessionCookie(token))
		response := httptest.NewRecorder()
		mux.ServeHTTP(response, request)
		result := response.Result()
		assert.Equal(t, http.StatusOK, result.StatusCode)
		body, err := io.ReadAll(result.Body)
		assert.Nil(t, err)
		assert.Equal(t, conveyearthgo.ErrDeletionNotPermitted.Error()+authtest.TEST_USERNAME+conveytest.TEST_TOPIC+authtest.TEST_USERNAME, string(body))
	})
	t.Run("Gift As Author", func(t *testing.T) {
		db := database.NewInMemory()
		ev := authtest.NewEmailVerifier()
		auth := authgo.NewAuthenticator(db, ev)
		acc := authtest.NewTestAccount(t, auth)
		token, _ := authtest.SignIn(t, auth)
		am := conveyearthgo.NewAccountManager(db)
		cm := conveyearthgo.NewContentManager(db, fs)
		c, m, _ := conveytest.NewConversation(t, cm, acc)
		g := conveytest.NewGift(t, cm, acc, c, m)
		mux := http.NewServeMux()
		handler.AttachDeleteHandler(mux, auth, am, cm, tmpl)
		request := httptest.NewRequest(http.MethodPost, fmt.Sprintf("/delete?conversation=%d&gift=%d", c.ID, g.ID), nil)
		request.AddCookie(auth.NewSignInSessionCookie(token))
		response := httptest.NewRecorder()
		mux.ServeHTTP(response, request)
		result := response.Result()
		assert.Equal(t, http.StatusFound, result.StatusCode)
		u, err := result.Location()
		assert.Nil(t, err)
		assert.Equal(t, fmt.Sprintf("/conversation?id=%d#message%d", c.ID, m.ID), u.String())
	})
	// TODO Gift Not Author
}
